index/urls.py
from django.urls import path
from .views import ContactView, ContactSuccessView

app_name = 'index'

urlpatterns = [
    path('', ContactView.as_view(), name="contact"),
    path('success/', ContactSuccessView.as_view(), name="success"),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls'))
]

index/models.py
from django.db import models

index/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth import  get_user_model
import randfacts
 
 





class ContactForm(forms.Form):

    name = forms.CharField(max_length=120)
    email = forms.EmailField()

    def get_info(self):
        """
        Method that returns formatted information
        :return: subject, msg
        """
        # Cleaned data
        cl_data = super().clean()

        name = cl_data.get('name').strip()
        subject = "Random Fact"

        msg = f'Hi {name},\n\n'
        msg += f'Did you know that?\n'
        msg += f"{randfacts.get_fact()}\n\n"
        msg += "Enjoy,\n"
        msg += "Yusuf AbdulHakeem A."
        return subject, msg

    def send(self):

        subject, msg = self.get_info()
        cl_data = super().clean()
        email = cl_data.get('email')

        send_mail(
            subject=subject,
            message=msg,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[email]
        )

index/views.py
from django.shortcuts import render
from django.views.generic import FormView, TemplateView
from .forms import ContactForm
from django.urls import reverse_lazy


class ContactView(FormView):
    template_name = 'contact/contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('index:success')

    def form_valid(self, form):
        # Calls the custom send method
        form.send()
        return super().form_valid(form)


class ContactSuccessView(TemplateView):
    template_name = 'contact/success.html'

index/templates/contact/base.html
<!-- contact/templates/contact/base.html -->
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Get Random Facts</title>
    <link rel="stylesheet" type="text/css" href="{% static 'index/css/bootstrap.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous" />
  </head>

  <body>
    {% block body %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous">
    </script>
  </body>

</html>

index/templates/contact/contact.html
{% extends 'contact/base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="mx-auto my-4 text-center">
    <h1>Get Random Facts</h1>
</div>
<div class="container d-flex align-items-center justify-content-center">
    <form action="" method="post">
        {% csrf_token %}
        {{ form | crispy }}
    <button class="btn btn-success my-3" type="submit">Get Fact</button>
    </form>
</div>
{% endblock %}

index/templates/contact/register.html
{% extends 'contact/base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="mx-auto my-4 text-center">
    <h1>Contact Me</h1>
</div>
<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        {{ form | crispy }}
    <button class="btn btn-success my-3" type="submit">REGISTER</button>
    </form>
    If you already have an account <a href="/login" target="blank"><strong>Login here</strong></a> instead.

</div>
{% endblock %}

index/templates/contact/success.html
{% extends 'contact/base.html' %}

{% block body %}
<div class="mx-auto my-4 text-center">
    <h1 class="fw-bolder text-success">We sent you a random fact</h1>
    <p class="my-5">You can send another in the <a href="{% url 'index:contact' %}">fact page</a></p>
</div>
{% endblock %}